{
 "title": "JVM Broadcaster",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Total Heap Memory",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\"}) by (instance_label)",
     "legendFormat": "Used - {{instance_label}}"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{area=\"heap\"}) by (instance_label)",
     "legendFormat": "Commited - {{instance_label}}"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{area=\"heap\"}) by (instance_label)",
     "legendFormat": "Max - {{instance_label}}"
    }
   ]
  },
  {
   "title": "Total Non-Heap Memory",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"nonheap\"}) by (instance_label)",
     "legendFormat": "Used - {{instance_label}}"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{area=\"nonheap\"}) by (instance_label)",
     "legendFormat": "Committed - {{instance_label}}"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{area=\"nonheap\"}) by (instance_label)",
     "legendFormat": "Max - {{instance_label}}"
    }
   ]
  },
  {
   "title": "Eden Space (Heap)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{id=\"G1 Eden Space\"}",
     "legendFormat": "Used - {{instance_label}}"
    },
    {
     "expr": "jvm_memory_committed_bytes{id=\"G1 Eden Space\"}",
     "legendFormat": "Committed - {{instance_label}}"
    },
    {
     "expr": "jvm_memory_max_bytes{id=\"G1 Eden Space\"}",
     "legendFormat": "Max - {{instance_label}}"
    }
   ]
  },
  {
   "title": "Survivor Space (Heap)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{id=\"G1 Survivor Space\"}",
     "legendFormat": "Used - {{instance_label}}"
    },
    {
     "expr": "jvm_memory_committed_bytes{id=\"G1 Survivor Space\"}",
     "legendFormat": "Committed - {{instance_label}}"
    },
    {
     "expr": "jvm_memory_max_bytes{id=\"G1 Survivor Space\"}",
     "legendFormat": "Max - {{instance_label}}"
    }
   ]
  },
  {
   "title": "Old Generation (Heap)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{id=\"G1 Old Gen\"}",
     "legendFormat": "Used - {{instance_label}}"
    },
    {
     "expr": "jvm_memory_committed_bytes{id=\"G1 Old Gen\"}",
     "legendFormat": "Committed - {{instance_label}}"
    },
    {
     "expr": "jvm_memory_max_bytes{id=\"G1 Old Gen\"}",
     "legendFormat": "Max - {{instance_label}}"
    }
   ]
  },
  {
   "title": "Metaspace (Non-Heap)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{id=\"Metaspace\"}",
     "legendFormat": "Used - {{instance_label}}"
    },
    {
     "expr": "jvm_memory_committed_bytes{id=\"Metaspace\"}",
     "legendFormat": "Committed - {{instance_label}}"
    },
    {
     "expr": "jvm_memory_max_bytes{id=\"Metaspace\"}",
     "legendFormat": "Max - {{instance_label}}"
    }
   ]
  },
  {
   "title": "Compressed Class Space (Non-Heap)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{id=\"Compressed Class Space\"}",
     "legendFormat": "Used - {{instance_label}}"
    },
    {
     "expr": "jvm_memory_committed_bytes{id=\"Compressed Class Space\"}",
     "legendFormat": "Committed - {{instance_label}}"
    },
    {
     "expr": "jvm_memory_max_bytes{id=\"Compressed Class Space\"}",
     "legendFormat": "Max - {{instance_label}}"
    }
   ]
  },
  {
   "title": "CodeHeap 'profiled nmethods' (Non-Heap)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{id=\"CodeHeap 'profiled nmethods'\"}",
     "legendFormat": "Used - {{instance_label}}"
    },
    {
     "expr": "jvm_memory_committed_bytes{id=\"CodeHeap 'profiled nmethods'\"}",
     "legendFormat": "Committed - {{instance_label}}"
    },
    {
     "expr": "jvm_memory_max_bytes{id=\"CodeHeap 'profiled nmethods'\"}",
     "legendFormat": "Max - {{instance_label}}"
    }
   ]
  },
  {
   "title": "CodeHeap 'non-profiled nmethods' (Non-Heap)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{id=\"CodeHeap 'non-profiled nmethods'\"}",
     "legendFormat": "Used - {{instance_label}}"
    },
    {
     "expr": "jvm_memory_committed_bytes{id=\"CodeHeap 'non-profiled nmethods'\"}",
     "legendFormat": "Committed - {{instance_label}}"
    },
    {
     "expr": "jvm_memory_max_bytes{id=\"CodeHeap 'non-profiled nmethods'\"}",
     "legendFormat": "Max - {{instance_label}}"
    }
   ]
  },
  {
   "title": "CodeHeap 'non-nmethods' (Non-Heap)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{id=\"CodeHeap 'non-nmethods'\"}",
     "legendFormat": "Used - {{instance_label}}"
    },
    {
     "expr": "jvm_memory_committed_bytes{id=\"CodeHeap 'non-nmethods'\"}",
     "legendFormat": "Committed - {{instance_label}}"
    },
    {
     "expr": "jvm_memory_max_bytes{id=\"CodeHeap 'non-nmethods'\"}",
     "legendFormat": "Max - {{instance_label}}"
    }
   ]
  },
  {
   "title": "Memory Allocation/Promotion Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_gc_memory_allocated_bytes_total[1m])",
     "legendFormat": "Allocated - {{instance_label}}"
    },
    {
     "expr": "irate(jvm_gc_memory_promoted_bytes_total[1m])",
     "legendFormat": "Promoted - {{instance_label}}"
    }
   ]
  },
  {
   "title": "Minor GC Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_pause_seconds_count{action=\"end of minor GC\"}[1m])",
     "legendFormat": "Minor GC - {{instance_label}}"
    }
   ]
  },
  {
   "title": "Major GC Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_pause_seconds_count{action=\"end of major GC\"}[1m])",
     "legendFormat": "Major GC - {{instance_label}}"
    }
   ]
  },
  {
   "title": "AVG/MAX GC Pause Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum[1m])/rate(jvm_gc_pause_seconds_count[1m])",
     "legendFormat": "AVG {{action}} ({{cause}}) - {{instance_label}}"
    },
    {
     "expr": "jvm_gc_pause_seconds_max",
     "legendFormat": "MAX {{action}} ({{cause}}) - {{instance_label}}"
    }
   ]
  },
  {
   "title": "Direct Buffers (Non-Heap)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{id=\"direct\"}",
     "legendFormat": "Used Bytes - {{instance_label}}"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{id=\"direct\"}",
     "legendFormat": "Capacity Bytes - {{instance_label}}"
    }
   ]
  },
  {
   "title": "Direct Mapped Buffers (Non-Heap)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{id=\"mapped\"}",
     "legendFormat": "Used Bytes - {{instance_label}}"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{id=\"mapped\"}",
     "legendFormat": "Capacity Bytes - {{instance_label}}"
    }
   ]
  },
  {
   "title": "Threads (Deamon/Live)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_threads_daemon_threads", "legendFormat": "Daemon - {{instance_label}}" },
    { "expr": "jvm_threads_live_threads", "legendFormat": "Live - {{instance_label}}" }
   ]
  },
  {
   "title": "Threads States",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_states_threads{state=\"runnable\"}",
     "legendFormat": "Runnable - {{instance_label}}"
    },
    {
     "expr": "jvm_threads_states_threads{state=\"blocked\"}",
     "legendFormat": "Blocked - {{instance_label}}"
    },
    {
     "expr": "jvm_threads_states_threads{state=\"waiting\"}",
     "legendFormat": "Waiting - {{instance_label}}"
    },
    {
     "expr": "jvm_threads_states_threads{state=\"timed-waiting\"}",
     "legendFormat": "Timed-Waiting - {{instance_label}}"
    },
    {
     "expr": "jvm_threads_states_threads{state=\"new\"}",
     "legendFormat": "New - {{instance_label}}"
    },
    {
     "expr": "jvm_threads_states_threads{state=\"terminated\"}",
     "legendFormat": "Terminated - {{instance_label}}"
    }
   ]
  },
  {
   "title": "Classes Loaded",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded_classes",
     "legendFormat": "Classes Loaded - {{instance_label}}"
    }
   ]
  },
  {
   "title": "Classes Unloaded",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 92 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_unloaded_classes_total",
     "legendFormat": "Classes Unloaded - {{instance_label}}"
    }
   ]
  }
 ]
}