{
 "title": "Netty Broadcaster",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Pooled Buffers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "netty_memory_pool_used_bytes{pool=\"direct\", type=\"pooled\"}",
     "legendFormat": "direct - {{instance}} - {{instance_label}}"
    },
    {
     "expr": "netty_memory_pool_used_bytes{pool=\"heap\", type=\"pooled\"}",
     "legendFormat": "heap - {{instance}} - {{instance_label}}"
    }
   ]
  },
  {
   "title": "Unpooled Buffers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "netty_memory_pool_used_bytes{pool=\"direct\", type=\"unpooled\"}",
     "legendFormat": "direct - {{instance}} - {{instance_label}}"
    },
    {
     "expr": "netty_memory_pool_used_bytes{pool=\"heap\", type=\"unpooled\"}",
     "legendFormat": "heap - {{instance}} - {{instance_label}}"
    }
   ]
  },
  {
   "title": "Connections Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "netty_connections_total",
     "legendFormat": "direct - {{instance}} - {{instance_label}}"
    }
   ]
  }
 ]
}