{
 "title": "SYSTEM Broadcaster",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Log Events - Error",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(logback_events_total{level=~\"error\"}[1m])",
     "legendFormat": "{{instance_label}} - {{level}}"
    }
   ]
  },
  {
   "title": "Log Events - Info/Warn/Error",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(logback_events_total{level=~\"error|warn|info\"}[1m])",
     "legendFormat": "{{instance_label}} - {{level}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_files_open_files",
     "legendFormat": "{{instance_label}} - Opened Files"
    }
   ]
  },
  {
   "title": "System Load Average",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load_average_1m",
     "legendFormat": "{{instance_label}} - Opened Files"
    },
    {
     "expr": "system_cpu_count",
     "legendFormat": "CPU Core Size - {{instance_label}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage",
     "legendFormat": "System CPU Usage - {{instance_label}}"
    },
    {
     "expr": "process_cpu_usage",
     "legendFormat": "Process CPU Usage - {{instance_label}}"
    }
   ]
  }
 ]
}